[package]
name = "gltf"
version = "0.7.0"
authors = ["alteous <alteous@outlook.com>"]
description = "glTF 2.0 loader"
documentation = "https://docs.rs/gltf"
repository = "https://github.com/alteous/gltf"
homepage = "https://github.com/alteous/gltf"
readme = "README.md"
keywords = ["glTF", "3D", "asset", "model", "scene"]
license = "MIT/Apache-2.0"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[badges]
travis-ci = { repository = "alteous/gltf" }

[dev-dependencies]
futures-cpupool = "0.1"

[dependencies]
base64 = "0.6"
futures = "0.1"
gltf-derive = "0.1"
image = "0.14"
lazy_static = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[features]
default = []
extras = []
names = []

[[example]]
name = "gltf-display"
path = "examples/display/main.rs"

